version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests
  build:
    commands:
      - echo Building, Testing and packaging the application...
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: target
  files:
      - '*.jar'
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'